### ISSUE TITLE
Ancestry not working properly for SBN in Prod

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-sweepers#171]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

https://pds.mcp.nasa.gov/api/search/1/products/urn:nasa:pds:nh_alice::2.0 contains 5 collections, however, https://pds.mcp.nasa.gov/api/search/1/products/urn:nasa:pds:nh_alice::2.0/members only returns 2

### 🕵️ Expected behavior

I expected all 5 to be returned

### 📜 To Reproduce

1. go to https://pds.mcp.nasa.gov/api/search/1/products/urn:nasa:pds:nh_alice::2.0
2. note ref_lid_collection has 5 collections
3. go to https://pds.mcp.nasa.gov/api/search/1/products/urn:nasa:pds:nh_alice::2.0/members
4. only 2 members are returned

notes:
* urn:nasa:pds:nh_alice::2.0 was loaded on 2025-06-10T15:23:09.937325698Z
* some of the collections are referenced by >1 bundle, but that doesn't appear to be the exact issue since one of the members returned, `urn:nasa:pds:nh_alice:calibration_files::1.0`, is appropriately referencing multiple bundles:

```
"ops:Provenance.ops:parent_bundle_identifier": [
"urn:nasa:pds:nh_alice::2.0",
"urn:nasa:pds:nh_alice::1.0"
],
```

### 🖥 Environment Info

internet

### 📚 Version of Software Used

latest production

### 🦄 Related requirements

🦄 #xyz

**Comment by alexdunnjpl** [comment]
Proximate cause is (almost certainly) that the sweepers have not successfully run against the relevant node (probably `sbnpsi`) since the new data was harvested.

Root cause is either that the sweepers were not succeeding due to the mappings issue fixed in #172, or there was insufficient memory assigned to the sbnpsi ECS container to complete ancestry sweep - it hits an OOM error when attempting to run from the deploy EC2.

Need to check whether sbnpsi can successfully complete in ECS, otherwise this is blocked by and should be resolved by #170

**Comment by jordanpadams** [comment]
@alexdunnjpl copy. thanks. that is what I was thinking as well. We should discuss how we can somehow get notified of this...

**Comment by alexdunnjpl** [comment]
@tbarnes4 there was one last corner-case to iron out (similar to above)

Am I correct in thinking that the collections were uploaded some period of time before the bundle label was updated to reflect the additional two collections as members?

I've written a fix to correctly detect this situation, and propagate stale status from an updated bundle to its member collections, which appears to resolve the issue, but I want to confirm with you that that's actually what occurred.

**Comment by alexdunnjpl** [comment]
Status: sweepers are being run one by one (@tloubrieu-jpl), issue is expected to be resolved upon completion

**Comment by tloubrieu-jpl** [comment]
Hi @alexdunnjpl, 
This still does not work after sweeper has run on SBNUMD node.

In opensearch, one of the collections member of the bundle has the property `ops:Provenance/ops:registry_sweepers_ancestry_version=7`, but the property `ops:Provenance/ops:ancestor_refs` is not assigned. The API in version 1.7 is expecting this value to be set to retrieve members of a bundle.

**Comment by alexdunnjpl** [comment]
See https://github.com/NASA-PDS/deep-archive/issues/255#issuecomment-5685058001

All five collections are returned, as expected

https://pds.mcp.nasa.gov/api/search/1/products/urn:nasa:pds:nh_alice::2.0/members

<img width="836" height="314" alt="Image" src="https://github.com/user-attachments/assets/9573e5cf-d526-49ea-9879-04a585559ad2" />
